background #170E12
foreground #F0DEE5
cursor #EEA8C0
selection_background #4A1C30
selection_foreground #F0DEE5
color0 #281520
color1 #F5A0A8
color2 #C07890
color3 #F0D47A
color4 #C878A0
color5 #EEA8C0
color6 #D898B8
color7 #F0DEE5
color8 #4A2838
color9 #F8B8C0
color10 #EEA8C0
color11 #F8E898
color12 #F0B8CC
color13 #F8C8D8
color14 #F8D0E0
color15 #FFFFFF
