#!/usr/bin/env bash
set -euo pipefail

THEME="${1:-material-ocean}"

case "$THEME" in
  material-ocean)
    BG="#1A1B20"
    TEXT="#E3E3E8"
    ACCENT="#8AB4F8"
    WARNING="#FDD663"
    CRITICAL="#F28B82"
    CHARGING="#81C995"
    BORDER_ACTIVE="8AB4F8cc"
    BORDER_INACTIVE="33353Aaa"
    KITTY_BG="#0F1115"
    KITTY_FG="#E3E3E8"
    KITTY_CURSOR="#8AB4F8"
    KITTY_SEL_BG="#2D4F7F"
    KITTY_SEL_FG="#E3E3E8"
    KITTY_COLOR0="#1A1B20"
    KITTY_COLOR1="#F28B82"
    KITTY_COLOR2="#81C995"
    KITTY_COLOR3="#FDD663"
    KITTY_COLOR4="#8AB4F8"
    KITTY_COLOR5="#C58AF9"
    KITTY_COLOR6="#78D9EC"
    KITTY_COLOR7="#E3E3E8"
    KITTY_COLOR8="#33353A"
    KITTY_COLOR9="#F28B82"
    KITTY_COLOR10="#A8DAB5"
    KITTY_COLOR11="#FDD663"
    KITTY_COLOR12="#AECBFA"
    KITTY_COLOR13="#D7AEFB"
    KITTY_COLOR14="#A1E4F2"
    KITTY_COLOR15="#FFFFFF"
    DUNST_NORMAL_BG="#1A1B20"
    DUNST_NORMAL_FG="#E3E3E8"
    DUNST_FRAME="#33353A"
    DUNST_LOW_BG="#1A1B20"
    DUNST_LOW_FG="#8E8E93"
    DUNST_WARN_BG="#1A1B20"
    DUNST_WARN_FG="#FDD663"
    DUNST_CRIT_BG="#F28B82"
    DUNST_CRIT_FG="#1A1B20"
    DUNST_CRIT_FRAME="#F28B82"
    ;;
  catppuccin-mocha)
    BG="#1E1E2E"
    TEXT="#CDD6F4"
    ACCENT="#89B4FA"
    WARNING="#F9E2AF"
    CRITICAL="#F38BA8"
    CHARGING="#A6E3A1"
    BORDER_ACTIVE="89B4FAcc"
    BORDER_INACTIVE="45475Aaa"
    KITTY_BG="#1E1E2E"
    KITTY_FG="#CDD6F4"
    KITTY_CURSOR="#F5E0DC"
    KITTY_SEL_BG="#45475A"
    KITTY_SEL_FG="#CDD6F4"
    KITTY_COLOR0="#45475A"
    KITTY_COLOR1="#F38BA8"
    KITTY_COLOR2="#A6E3A1"
    KITTY_COLOR3="#F9E2AF"
    KITTY_COLOR4="#89B4FA"
    KITTY_COLOR5="#CBA6F7"
    KITTY_COLOR6="#94E2D5"
    KITTY_COLOR7="#BAC2DE"
    KITTY_COLOR8="#585B70"
    KITTY_COLOR9="#F38BA8"
    KITTY_COLOR10="#A6E3A1"
    KITTY_COLOR11="#F9E2AF"
    KITTY_COLOR12="#89B4FA"
    KITTY_COLOR13="#CBA6F7"
    KITTY_COLOR14="#94E2D5"
    KITTY_COLOR15="#A6ADC8"
    DUNST_NORMAL_BG="#1E1E2E"
    DUNST_NORMAL_FG="#CDD6F4"
    DUNST_FRAME="#45475A"
    DUNST_LOW_BG="#1E1E2E"
    DUNST_LOW_FG="#A6ADC8"
    DUNST_WARN_BG="#1E1E2E"
    DUNST_WARN_FG="#F9E2AF"
    DUNST_CRIT_BG="#F38BA8"
    DUNST_CRIT_FG="#1E1E2E"
    DUNST_CRIT_FRAME="#F38BA8"
    ;;
  rose-pine-moon)
    BG="#232136"
    TEXT="#E0DEF4"
    ACCENT="#C4A7E7"
    WARNING="#F6C177"
    CRITICAL="#EB6F92"
    CHARGING="#9CCFD8"
    BORDER_ACTIVE="C4A7E7cc"
    BORDER_INACTIVE="393552aa"
    KITTY_BG="#232136"
    KITTY_FG="#E0DEF4"
    KITTY_CURSOR="#E0DEF4"
    KITTY_SEL_BG="#44415A"
    KITTY_SEL_FG="#E0DEF4"
    KITTY_COLOR0="#393552"
    KITTY_COLOR1="#EB6F92"
    KITTY_COLOR2="#9CCFD8"
    KITTY_COLOR3="#F6C177"
    KITTY_COLOR4="#C4A7E7"
    KITTY_COLOR5="#EA9A97"
    KITTY_COLOR6="#3E8FB0"
    KITTY_COLOR7="#E0DEF4"
    KITTY_COLOR8="#56526E"
    KITTY_COLOR9="#EB6F92"
    KITTY_COLOR10="#9CCFD8"
    KITTY_COLOR11="#F6C177"
    KITTY_COLOR12="#C4A7E7"
    KITTY_COLOR13="#EA9A97"
    KITTY_COLOR14="#3E8FB0"
    KITTY_COLOR15="#908CAA"
    DUNST_NORMAL_BG="#232136"
    DUNST_NORMAL_FG="#E0DEF4"
    DUNST_FRAME="#393552"
    DUNST_LOW_BG="#232136"
    DUNST_LOW_FG="#908CAA"
    DUNST_WARN_BG="#232136"
    DUNST_WARN_FG="#F6C177"
    DUNST_CRIT_BG="#EB6F92"
    DUNST_CRIT_FG="#232136"
    DUNST_CRIT_FRAME="#EB6F92"
    ;;
  *)
    echo "Unknown theme: $THEME"
    exit 1
    ;;
esac

# A) Write Waybar colors.css
cat > "$HOME/.config/waybar/colors.css" << CSSEOF
/* Auto-generated by apply-theme.sh — do not edit */
@define-color bg ${BG};
@define-color text ${TEXT};
@define-color accent ${ACCENT};
@define-color warning ${WARNING};
@define-color critical ${CRITICAL};
@define-color charging ${CHARGING};
CSSEOF
pkill -SIGUSR2 waybar || true

# B) Apply Kitty colors (live + persist)
KITTY_COLORS_FILE="$HOME/.config/kitty/theme-colors.conf"
cat > "$KITTY_COLORS_FILE" << KITTYEOF
background ${KITTY_BG}
foreground ${KITTY_FG}
cursor ${KITTY_CURSOR}
selection_background ${KITTY_SEL_BG}
selection_foreground ${KITTY_SEL_FG}
color0 ${KITTY_COLOR0}
color1 ${KITTY_COLOR1}
color2 ${KITTY_COLOR2}
color3 ${KITTY_COLOR3}
color4 ${KITTY_COLOR4}
color5 ${KITTY_COLOR5}
color6 ${KITTY_COLOR6}
color7 ${KITTY_COLOR7}
color8 ${KITTY_COLOR8}
color9 ${KITTY_COLOR9}
color10 ${KITTY_COLOR10}
color11 ${KITTY_COLOR11}
color12 ${KITTY_COLOR12}
color13 ${KITTY_COLOR13}
color14 ${KITTY_COLOR14}
color15 ${KITTY_COLOR15}
KITTYEOF
kitty @ set-colors --all --configured "$KITTY_COLORS_FILE" 2>/dev/null || true

# C) Apply Hyprland border colors
hyprctl keyword general:col.active_border "rgba(${BORDER_ACTIVE})" 2>/dev/null || true
hyprctl keyword general:col.inactive_border "rgba(${BORDER_INACTIVE})" 2>/dev/null || true

# D) Apply Dunst colors
awk -v low_bg="$DUNST_LOW_BG" -v low_fg="$DUNST_LOW_FG" \
    -v norm_bg="$DUNST_NORMAL_BG" -v norm_fg="$DUNST_NORMAL_FG" \
    -v crit_bg="$DUNST_CRIT_BG" -v crit_fg="$DUNST_CRIT_FG" -v crit_frame="$DUNST_CRIT_FRAME" \
    -v frame="$DUNST_FRAME" \
    'BEGIN { section = "global" }
     /^\[urgency_low\]/ { section = "low" }
     /^\[urgency_normal\]/ { section = "normal" }
     /^\[urgency_critical\]/ { section = "critical" }
     /^\[/ && !/^\[urgency/ { section = "other" }
     section == "global" && /^\s*frame_color\s*=/ { print "    frame_color = \"" frame "\""; next }
     section == "low" && /^\s*background\s*=/ { print "    background = \"" low_bg "\""; next }
     section == "low" && /^\s*foreground\s*=/ { print "    foreground = \"" low_fg "\""; next }
     section == "normal" && /^\s*background\s*=/ { print "    background = \"" norm_bg "\""; next }
     section == "normal" && /^\s*foreground\s*=/ { print "    foreground = \"" norm_fg "\""; next }
     section == "critical" && /^\s*background\s*=/ { print "    background = \"" crit_bg "\""; next }
     section == "critical" && /^\s*foreground\s*=/ { print "    foreground = \"" crit_fg "\""; next }
     section == "critical" && /^\s*frame_color\s*=/ { print "    frame_color = \"" crit_frame "\""; next }
     { print }' \
  "$HOME/.config/dunst/dunstrc" > /tmp/dunstrc.tmp \
  && mv /tmp/dunstrc.tmp "$HOME/.config/dunst/dunstrc"
pkill dunst 2>/dev/null; dunst &
