general {
    lock_cmd = pidof hyprlock || hyprlock
    unlock_cmd =
    before_sleep_cmd = pidof hyprlock || hyprlock
    after_sleep_cmd =
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

listener {
    timeout = 600
    on-timeout = pidof hyprlock || hyprlock
    on-resume =
}

listener {
    timeout = 900
    on-timeout = wlopm --off '*'
    on-resume = wlopm --on '*'
}