#!/bin/bash

# Get Volume
get_volume() {
	volume=$(wpctl get-volume @DEFAULT_SINK@ | awk '{print $2 * 100}')
	echo "$volume"
}

# Increase Volume
inc_volume() {
	wpctl set-volume -l 1 @DEFAULT_SINK@ 5%+
}

# Decrease Volume
dec_volume() {
	wpctl set-volume @DEFAULT_SINK@ 5%-
}

# Toggle Mute
toggle_mute() {
	wpctl set-mute @DEFAULT_SINK@ toggle
}

# Toggle Mic
toggle_mic() {
	wpctl set-mute @DEFAULT_SOURCE@ toggle
}

# Increase MIC Volume
inc_mic_volume() {
	wpctl set-volume -l 1 @DEFAULT_SOURCE@ 5%+
}

# Decrease MIC Volume
dec_mic_volume() {
	wpctl set-volume @DEFAULT_SOURCE@ 5%-
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_volume
elif [[ "$1" == "--inc" ]]; then
	inc_volume
elif [[ "$1" == "--dec" ]]; then
	dec_volume
elif [[ "$1" == "--toggle" ]]; then
	toggle_mute
elif [[ "$1" == "--toggle-mic" ]]; then
	toggle_mic
elif [[ "$1" == "--mic-inc" ]]; then
	inc_mic_volume
elif [[ "$1" == "--mic-dec" ]]; then
	dec_mic_volume
else
	get_volume
fi
